"""baseline schema

Revision ID: c851c65c8dd4
Revises: 
Create Date: 2026-08-05 04:41:34.333626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c851c65c8dd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_attr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autodidex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessions', db.types.JSONEncoded(), nullable=True),
    sa.Column('bank_details', db.types.JSONEncoded(), nullable=True),
    sa.Column('game_badges', db.types.JSONEncoded(), nullable=True),
    sa.Column('game_update_state', db.types.JSONEncoded(), nullable=True),
    sa.Column('overall_level', db.types.JSONEncoded(), nullable=True),
    sa.Column('store_items', db.types.JSONEncoded(), nullable=True),
    sa.Column('subject_badges', db.types.JSONEncoded(), nullable=True),
    sa.Column('subject_levels', db.types.JSONEncoded(), nullable=True),
    sa.Column('username', db.types.JSONEncoded(), nullable=True),
    sa.Column('end_date', db.types.PickleEncoded(), nullable=True),
    sa.Column('last_saved_habits', db.types.JSONEncoded(), nullable=True),
    sa.Column('last_saved_checkboxes', db.types.JSONEncoded(), nullable=True),
    sa.Column('first_date', db.types.PickleEncoded(), nullable=True),
    sa.Column('state', db.types.JSONEncoded(), nullable=True),
    sa.Column('subject_tracker', db.types.JSONEncoded(), nullable=True),
    sa.Column('weekly_progress', db.types.JSONEncoded(), nullable=True),
    sa.Column('config', db.types.JSONEncoded(), nullable=True),
    sa.Column('temp', db.types.JSONEncoded(), nullable=True),
    sa.Column('dashboard_config', db.types.JSONEncoded(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dark', sa.String(), nullable=True),
    sa.Column('light', sa.String(), nullable=True),
    sa.Column('neutral', sa.String(), nullable=True),
    sa.Column('chosen theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overall_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('bank',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lumens', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user_info.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('cerebral_pursuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('subject_xp', sa.Integer(), nullable=False),
    sa.Column('subject_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user_info.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges_and_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('titles', sa.String(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['cerebral_pursuits.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user_info.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_marks',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.String(), nullable=True),
    sa.Column('Monday', sa.String(), nullable=True),
    sa.Column('Tuesday', sa.String(), nullable=True),
    sa.Column('Wednesday', sa.String(), nullable=True),
    sa.Column('Thursday', sa.String(), nullable=True),
    sa.Column('Friday', sa.String(), nullable=True),
    sa.Column('Saturday', sa.String(), nullable=True),
    sa.Column('Sunday', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['cerebral_pursuits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('note_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_note_id', sa.Integer(), nullable=False),
    sa.Column('target_note_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_note_id', 'target_note_id', name='uq_note_link_pair')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('remind_at', sa.String(), nullable=False),
    sa.Column('fired', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('idx_reminders_remind_at', ['remind_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('idx_reminders_remind_at')

    op.drop_table('reminders')
    op.drop_table('note_links')
    op.drop_table('check_marks')
    op.drop_table('badges_and_titles')
    op.drop_table('notes')
    op.drop_table('cerebral_pursuits')
    op.drop_table('bank')
    op.drop_table('user_info')
    op.drop_table('themes')
    op.drop_table('notebooks')
    op.drop_table('autodidex')
    op.drop_table('app_attr')
    # ### end Alembic commands ###
